<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            //$items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;

        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            //related categories
            $categories = array(
                array("id"=>21,"name"=>"Forks","class"=>'forks_related'),
                array("id"=>5,"name"=>"Wheelsets","class"=>'wheelsets_related'),
                array("id"=>12,"name"=>"Pedals","class"=>'pedals_related'),
                array("id"=>13,"name"=>"Cranksets","class"=>'cranksets_related'),
                array("id"=>20,"name"=>"Headsets","class"=>'headsets_related'),
                array("id"=>19,"name"=>"Seatposts","class"=>'seatposts_related'),
                array("id"=>15,"name"=>"Seatpost Clamps","class"=>'clamps_related'),
                array("id"=>6,"name"=>"Shirts|Hats","class"=>'shirts_related'),
            );
            $_product= $block->getProduct();
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>
<?php $related = array(); ?>
<?php if ($exist):?>

<div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2">Components - </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">

        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">

            <?php foreach($categories as $category): ?>

                <?php
                $catImage = '';
                //get items for category
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                //get category
                $_cat = $objectManager->get('Magento\Catalog\Model\Category')->load($category["id"]);
                $catImage = $_cat->getImageUrl();

                //get related products
                $_ritems = $objectManager->get('Magento\Catalog\Model\Product')->getCollection()
                    ->addAttributeToSelect('*')
                    ->addAttributeToFilter('entity_id', array('in' => $_product->getRelatedProductIds()));

                $_ritems->joinTable(
                    array('category' => 'catalog_category_product'), 'product_id=entity_id',
                    array('category_id' => 'category_id'),
                    'category_id = '.$category["id"]
                );
                $icount = clone $_ritems;
                if($icount->count() > 0 ):
                    //add to js array
                    $related[] = $category["class"];
                    ?>
                    <div class="related-products container">
                        <span class="related-products category"> <?= $category["name"]; ?></span>
                        <select class="related-products select" name="related-products[]" id="<?= $category["class"]; ?>">
                            <?php $iterator = 1; ?>
                            <option class="related-option" <?php if($catImage != '') echo 'data-image="'. $catImage.'"'; ?> value="">
                            </option>
                            <?php foreach ($_ritems->load() as $_ritem): ?>

                                <?php
                                //$image = 'category_page_grid' or 'category_page_list';
                                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                $productImage = $_imagehelper->init($_ritem, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(100)->getUrl();
                                ?>
                                <option class="related-option" data-image="<?= $productImage; ?>" value="<?= $_ritem->getId(); ?>">
                                    <?php echo $block->escapeHtml($_ritem->getName()) ?> -
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_ritem); ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                <?php endif; ?>
            <?php endforeach ?>
        </div>
    </div>
</div>
<?php endif;?>


            <script type="text/javascript">
                require(['jquery','jqueryDropdown'],function($){
                    $(window).load(function() {
                        <?php foreach($related as $cls): ?>
                        $("#<?= $cls; ?>").msDropdown();
                        <?php endforeach; ?>
                    });

                });
            </script>
